### ISSUE TITLE
Why tuned GLM confusion matrix has less records

### ISSUE THREAD

**Issue by ChuliangXiao** [h2oai/tutorials#143] opened 2020-07-25 01:15 UTC
https://h2oai.github.io/tutorials/introduction-to-machine-learning-with-h2o-3-part-1/#8

![](https://h2oai.github.io/tutorials/introduction-to-machine-learning-with-h2o-3-part-1/img/9c08a7585c44c018.jpg)

As in the split
```python
print("train:%d valid:%d test:%d" % (train.nrows, valid.nrows, test.nrows))
````
Output:
> train:350268 valid:**74971** test:74898

And this only happens in turned GLM not in RF or GBM.

**Comment by Castro38** [comment] 2020-07-25 01:23
Hi @ChuliangXiao, thank you for reaching out to us. We will review your question and respond promptly. 

Thank you.

H2O.ai Tutorials Team

**Comment by FrankJVA** [comment] 2020-07-29 00:44
Hi @ChuliangXiao, we are updating this tutorial and we will take a look at this. Thank you for pointing this out. 

H2O.ai Tutorials Team

**Comment by FrankJVA** [comment] 2020-08-10 22:29
Hi @ ChuliangXiao,

After reviewing this issue, we found out that this is an internal issue with the generation of the confusion matrix, and our team is already working on resolving this issue. Thank you once again for your contribution! We appreciate your help. Once the issue is resolved, we will be updating the tutorial. 

H2O.ai Tutorials Team

**Closed by FrankJVA** 2020-08-10 22:29 UTC
